In [1]:
from scipy import mgrid
data1 = mgrid[0:5,0:5]

In [3]:
print( data1)


[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]


In [4]:
print(type(data1))

<class 'numpy.ndarray'>


In [5]:
print(data1.ndim)

3


In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
a.ndim


2

In [5]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# slicing in array 

# extract only 0 and 1 row from the metrics 

a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#extract 2 index element from the 0 and 1 row
a[0:2,2]

array([3, 6])

In [9]:
# extract only last row 
a[-1]

array([7, 8, 9])

In [10]:
# extract all rows 1 index element

a[:,1]

array([2, 5, 8])

In [13]:
#flatten the numpy dimensional array 

for elem in a.flat:
    print(elem)

1
2
3
4
5
6
7
8
9


In [19]:
#vertical and horizantal stacking of 2 arrays 

arr1 = np.arange(10).reshape(5,2)
arr2 = np.arange(10,20).reshape(5,2)

In [20]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
arr2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [23]:
np.vstack((arr1,arr2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [24]:
np.hstack((arr2,arr1))

array([[10, 11,  0,  1],
       [12, 13,  2,  3],
       [14, 15,  4,  5],
       [16, 17,  6,  7],
       [18, 19,  8,  9]])

In [25]:
#split arrany into 3 arrays 

In [27]:
arr3 = np.arange(25).reshape(5,5)

In [28]:
arr3


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
res = np.hsplit(arr3,5)

In [33]:
print(res[0],res[1],res[2],res[3],res[4])

[[ 0]
 [ 5]
 [10]
 [15]
 [20]] [[ 1]
 [ 6]
 [11]
 [16]
 [21]] [[ 2]
 [ 7]
 [12]
 [17]
 [22]] [[ 3]
 [ 8]
 [13]
 [18]
 [23]] [[ 4]
 [ 9]
 [14]
 [19]
 [24]]


In [34]:
#vertical spliting 
res1 =np.vsplit(arr3,5)

In [35]:
res1

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [36]:
# boolean stricks 
b = a>5

In [37]:
a[b]

array([6, 7, 8, 9])

In [38]:
a[b] =-1

In [39]:
a


array([[ 1,  2,  3],
       [ 4,  5, -1],
       [-1, -1, -1]])

In [43]:
np.r_[3,[0]*5,-1:1:10j]   

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

In [52]:
row_concat=np.r_[[3,4,5],[7,8,9]] 
print(row_concat.ndim)
print(row_concat)

1
[3 4 5 7 8 9]


In [53]:
col_concat=np.c_[[3,4,5],[7,8,9]]
print(col_concat.ndim)
print(col_concat)

2
[[3 7]
 [4 8]
 [5 9]]


In [50]:
col_concat.ndim

2

In [58]:
mgrid_sam = np.mgrid[0:4,0:4]

In [59]:
mgrid_sam.ndim

3

In [62]:
pr = np.poly1d([3,4,5])
print(pr)

   2
3 x + 4 x + 5


In [63]:
print(pr*pr)

   4      3      2
9 x + 24 x + 46 x + 40 x + 25
